name: Generate tag

on:
  schedule:
    - cron: "0 0 15 * *"
  workflow_dispatch:

jobs:
  release:
    name: Release tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ github.run_number }}" -m "Monthly release r${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"
